CREATE TABLE `CRIMINOSO` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` varchar(50) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `ARMA` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`classe` varchar(32) NOT NULL,
	`nome` varchar(32) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `VITIMA` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` varchar(50) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `CRIME` (
	`id` BINARY NOT NULL AUTO_INCREMENT,
	`criminoso_id` BINARY NOT NULL,
	`vitima_id` BINARY NOT NULL,
	`arma_id` BINARY NOT NULL,
	PRIMARY KEY (`id`)
);

ALTER TABLE `CRIME` ADD CONSTRAINT `CRIME_fk0` FOREIGN KEY (`criminoso_id`) REFERENCES `CRIMINOSO`(`id`);

ALTER TABLE `CRIME` ADD CONSTRAINT `CRIME_fk1` FOREIGN KEY (`vitima_id`) REFERENCES `VITIMA`(`id`);

ALTER TABLE `CRIME` ADD CONSTRAINT `CRIME_fk2` FOREIGN KEY (`arma_id`) REFERENCES `ARMA`(`id`);





